name: "Build & Release"

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main
    secrets:
      CARGO_REGISTRY_TOKEN:
        description: "Token to publish to crates.io"
        required: true

jobs:
  run-ci:
    needs: validate-input
    uses: ./.github/workflows/ci.yaml

  release-plz:
    name: Release-plz
    needs: run-ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}